### PR TITLE
Fixed Save interfaces and functionality, Refactored code

### LINKED ISSUE #117: Keep Saved state for individual hikes when re-opening page
When you save a hike and refresh, the save button reverts back to as if it's not saved, but it is still saved in DB. 

Estimated time: 1 day
Actual time: 1 day

### LINKED ISSUE #123: Display saved hikes as accessible cards in profile page
Estimated time: 1 day
Actual time: 1 day

### PR DESCRIPTION
**Pull request by MaggieYang57**
### Saved Trails now display as cards
Cards from the HikeFinder interface are now displayed for saved hikes instead of a list of titles

image

### Fixed save button bug 
Button icon now reflects whether or not the hike is saved even when exiting the page

### Cleaned up backend
Deleted some old comments, also tried to switch user_type into userType to address ESLint's camelCase error

### Undid login changes, added to logout
Reverted userType changes - it not only created some bugs, but it create additional internal inconsistencies due to our database saving the variable as "user_type", and changing it at this point would be somewhat risky. Also made the logout button remove _id from localStorage since it is left over from the logged in user

### Fixed save button for not logged in users
Added a check so system doesn't look if the hike is saved if not logged in

### Changed color of review button, refactored css
A QA report mentioned that the "Write a Review" button didn't have a very strong contrast in color, so I changed the color and also deleted unnecessary css

image

Closes #117 
Closes #123

### CODE REVIEW

File: frontend/src/ProfilePage.js [hunk 1]
```diff
@@ -9,41 +11,68 @@ const backendHostURL = process.env.REACT_APP_BACKEND_HOST_URL
...
+  {
+    for (let i =0; i < this.state.data.saved_trails.length; i++)
+    {
+      const savedTrail = this.state.data.saved_trails[i]
+    
+      fetch(`${backendHostURL}/hike/${savedTrail}`, {
+      }).then((res) => res.json())
+      .then((data) => {
+        const added = this.state.hikeCard.concat(data[0])
+        this.setState({hikeCard: added})
```
Comment (Baagi) [inline frontend/src/ProfilePage.js:39]: Does this mean we are setting the state for `hikeCard` multiple times until the loop ends? Just curious.

File: frontend/src/SinglePage.js [hunk 2]
```diff
@@ -19,19 +20,51 @@ const averageRatings = (ratings) => {
...
+        this.setState({ user: this.state.user.concat(data[0]) });
+        console.log("user", this.state.user)
+        if(this.state.user.length > 0)
+        {          
+          const hike = this.state.data._id
+          const length = this.state.user[0].saved_trails.length
+          for(let i = 0; i < length; i++)
+          {
+              const curr = this.state.user[0].saved_trails[i]
+              console.log(curr)
```
Comment (Baagi) [inline frontend/src/SinglePage.js]: maybe we should remove some console logs 😅

File: frontend/src/SinglePage.js [hunk 3]
```diff
@@ -50,36 +83,39 @@ class SinglePage extends React.Component {
...
       this.state.rating.push(rate);
       document.getElementById("rating-num").innerText = averageRatings(
-        this.state.rating
+        this.state.data.rating
       );
     });
   };
 
   render() {
+    console.log(this.state.saved)
```
Comment (Baagi) [inline frontend/src/SinglePage.js:93]: same here

File: frontend/src/components/singlepage/SaveButton.js [hunk 4]
```diff
@@ -10,39 +10,22 @@ const backendHostURL = process.env.REACT_APP_BACKEND_HOST_URL
...
-        }
+    async componentDidMount() {
+        await fetch(`${backendHostURL}/login/${localStorage.getItem("_id")}`)
+          .then((res) => res.json())
+          .then((data) => {
+            console.log("data", data);
+            this.setState({ ...data[0] });
+          });
+        this.setState({saved: this.props.saved})
+        console.log(this.state)
```
Comment (Baagi) [inline frontend/src/components/singlepage/SaveButton.js:24]: this looks so neat 👍

File: frontend/src/components/singlepage/SaveButton.js [hunk 5]
```diff
@@ -10,39 +10,22 @@ const backendHostURL = process.env.REACT_APP_BACKEND_HOST_URL
...
     }
```
Comment (Baagi) [inline frontend/src/components/singlepage/SaveButton.js]: Nice! 👍

File: backend/routes/hike.js [hunk 6]
```diff
@@ -69,61 +64,6 @@ router.post('/', (req, res) => {
...
-//           reviews: { _id: req.params.reviewID }
-//         }
-//       }
-//     )
-//     res.json({ Response: 'Review is deleted' })
-//   } catch (err) {
-//     res.json({ message: err })
-//   }
-// })
-
```
Comment (Baagi) [inline backend/routes/hike.js:126]: Thanks for doing this! 👍

File: frontend/src/ProfilePage.js [hunk 7]
```diff
@@ -9,41 +11,68 @@ const backendHostURL = process.env.REACT_APP_BACKEND_HOST_URL
...
 
   componentDidMount() {
     fetch(`${backendHostURL}/login/${localStorage.getItem("_id")}`)
       .then((res) => res.json())
       .then((data) => {
-        console.log("data", data);
-        this.setState({ ...data[0] });
+        this.setState({ data: data[0] });
+        this.getHikeCards()
+        console.log(this.state.hikeCard)
```
Comment (Baagi) [inline frontend/src/ProfilePage.js]:
```suggestion
````

File: frontend/src/SinglePage.js [hunk 8]
```diff
@@ -19,19 +20,54 @@ const averageRatings = (ratings) => {
...
+          this.setState({ user: this.state.user.concat(data[0]) });
+          console.log("user", this.state.user)
+          if(this.state.user.length > 0)
+          {          
+            const hike = this.state.data._id
+            const length = this.state.user[0].saved_trails.length
+            for(let i = 0; i < length; i++)
+            {
+                const curr = this.state.user[0].saved_trails[i]
+                console.log(curr)
```
Comment (Baagi) [inline frontend/src/SinglePage.js]:
```suggestion
````

File: frontend/src/SinglePage.js [hunk 9]
```diff
@@ -19,19 +20,54 @@ const averageRatings = (ratings) => {
...
+                if (curr === hike)
+                {
+                  this.setState({saved: true})
+                  console.log(this.state.saved)
```
Comment (Baagi) [inline frontend/src/SinglePage.js]:
```suggestion
````

File: frontend/src/components/singlepage/SaveButton.js [hunk 10]
```diff
@@ -10,39 +10,22 @@ const backendHostURL = process.env.REACT_APP_BACKEND_HOST_URL
...
-                })
-                .catch((err) => {
-                    console.log("Error");
-                });
-        }
+    async componentDidMount() {
+        await fetch(`${backendHostURL}/login/${localStorage.getItem("_id")}`)
+          .then((res) => res.json())
+          .then((data) => {
+            console.log("data", data);
```
Comment (Baagi) [inline frontend/src/components/singlepage/SaveButton.js]:
```suggestion
````

File: frontend/src/components/singlepage/SaveButton.js (hunk 4 above)
Comment (Baagi) [inline frontend/src/components/singlepage/SaveButton.js]:
```suggestion
````

File: frontend/src/components/singlepage/SaveButton.js [hunk 11]
```diff
@@ -10,39 +10,22 @@ const backendHostURL = process.env.REACT_APP_BACKEND_HOST_URL
...
+            this.setState({ ...data[0] });
+          });
+        this.setState({saved: this.props.saved})
+        console.log(this.state)
     }
 
-
     saveHike = () => {
+        console.log(this.props.hike)
```
Comment (Baagi) [inline frontend/src/components/singlepage/SaveButton.js]:
```suggestion
````

File: frontend/src/components/singlepage/SaveButton.js [hunk 12]
```diff
@@ -103,6 +86,7 @@ class SaveButton extends Component {
     }
 
     render() {
+        console.log(this.state.saved)
```
Comment (Baagi) [inline frontend/src/components/singlepage/SaveButton.js]:
```suggestion
````

**Comment by Baagi** [comment]
Nice job, Maggie! Everything looks good to me. Thanks for adding the cypress files in this PR. 

Minor: maybe removing some of the console.logs would be cleaner for later.

File: frontend/src/ProfilePage.js (hunk 1 above)
Comment (MaggieYang57) [reply frontend/src/ProfilePage.js:39]: Yeah, incrementally adding on to state.hikeCard was the only way I could get the HikeCardList component to read the array properly.

File: frontend/src/SinglePage.js (hunk 2 above)
Comment (MaggieYang57) [reply frontend/src/SinglePage.js]: True! I thought I deleted most of them but there were definitely some still left behind

File: frontend/src/SinglePage.js [hunk 13]
```diff
@@ -44,27 +44,30 @@ class SinglePage extends React.Component {
...
-          for(let i = 0; i < length; i++)
-          {
-              const curr = this.state.user[0].saved_trails[i]
-              console.log(curr)
-              if (curr === hike)
-              {
-                this.setState({saved: true})
-                console.log(this.state.saved)
-              }
+    if (localStorage.getItem("isLoggedIn") === "true")
```
Comment (srietkerk) [inline frontend/src/SinglePage.js:47]: This is awesome! It looks like this is where you fix the bug of the saved hike. Was this line of checking the local storage for the logged-in user the line that fixed it? 

Also, what does the this.state.user.concat(data[0]) concatenate to?

File: frontend/src/ProfilePage.js (hunk 1 above)
Comment (srietkerk) [reply frontend/src/ProfilePage.js:39]: Yeah, that's interesting. I'm guessing you tried to just append to a temporary list and then just set the state of the hikeCard list to the temporary one but that didn't work, which would probably take as much time as your current implementation now that I think about it. This added feature is really awesome. 

Also, it might help to rename the state variable to hikeCards since it holds the list.

**Review by srietkerk — COMMENTED** [review]
Hey Maggie, one thing I noticed was that the install cypress commit was pretty large. We can maybe add the Cypress examples folder to the .gitignore. 

Other than that, everything looks great! I left a couple of comments in some places, but they were more questions than anything. Thanks for cleaning up the code base, too!

File: frontend/src/SinglePage.js (hunk 13 above)
Comment (MaggieYang57) [reply frontend/src/SinglePage.js:47]: This check was to keep the button as unsaved if you aren't logged in. The bug was fixed by properly adding the saved hikes to the state array and passing it down to the button component !
Because I made this.state.user as an array, this.state.user.concat(data[0]) adds the user info to the state in a readable manner for checking saved hikes - other approaches like this.setState({user: data[0]}) didn't seem to work

**Comment by MaggieYang57** [comment]
@srietkerk trying to respond to your last comment but yeah hikeCards would probably make more sense since it can hold multiple saved hikes! I'll fix that in a future PR

File: frontend/src/ProfilePage.js (hunk 1 above)
Comment (MaggieYang57) [reply frontend/src/ProfilePage.js:39]: Yeah you're right hikeCards would make more sense since it can hold multiple hikes! I'll probably address that in a future PR

File: frontend/src/SinglePage.js (hunk 13 above)
Comment (srietkerk) [reply frontend/src/SinglePage.js:47]: Nice!

Ah, that makes sense. Yeah, I feel like state is weird sometimes.

**Review by sky-kurth — COMMENTED** [review]
Code looks good! Great implementation of the saved trails with consistent UI design. :)

File: frontend/src/ProfilePage.js (hunk 1 above)
Comment (MaggieYang57) [reply frontend/src/ProfilePage.js:39]: addressed in https://github.com/MaggieYang57/CSC308-TeamB/pull/129/commits/0d2c481d5c5212ca67bbb472c2d5e205088055f2
